public with sharing class PrimitiveTypes {
    public PrimitiveTypes() {
        String FirstName = 'Tom';
        System.debug('FirstName:' + FirstName);
        Integer QuantityOfPets = 1;
        System.debug('QuantityOfPets:' + quantityOfPets);
        Decimal Age = 29.5;
        System.debug('Age:' + Age);
        Boolean IsInJourney = false;
        System.debug('IsInJourney:' + IsInJourney);
        // Id - any valid 18-character Salesforce record ID.
        Id contactId = '00300000003T2PGAA0';
        System.debug('contactId:' + contactId);
    }

    public static void StringMethods() {
        String FirstName = 'Tom';
        FirstName.
    }
}